### ISSUE TITLE
Support for Vic-20 (Xvic)?

### ISSUE THREAD

**Issue by NikolaiHampton** [kodi-game/game.libretro.vice_x64#5]
### Describe the bug
There is no option in the add-on to specify the Xvic emulator. It doesn’t seem to be compiled into the .so library file either. 

Is this a distro specific issue (LibreELEC), or is it a build option in the Kodi game libretro add-on?

**Comment by lrusak** [comment]
Looking at the source only one type can be built at a time.
https://github.com/libretro/vice-libretro#build-instructions

Is there a reason you want Xvic vs x64 (the default)?

**Comment by NikolaiHampton** [comment]
Does x64 have support for the Vic20?
The settings for the emulator allow me to chose various Commodore 64 and PET platforms but not a Vic20.

**Comment by NikolaiHampton** [comment]
Yeah I had a look and it seems it'll need a new game.libretro.____xvic core all together.

I was a bit confused as I was assuming the core "game.libretro.vice" would support the whole Commodore series of machines just like vice does, but exploring the Libretro Buildbot output, it seems that they're building vice_x64...;  vice_xvic... etc.

So, other than the naming convention, I guess this is not an issue specifically for game.libretro.vice - happy for this to be closed if you guys don't think it's appropriate for here.

**Comment by NikolaiHampton** [comment]
Yep! That's them!

**Comment by garbear** [comment]
Done: https://github.com/kodi-game/kodi-game-scripting/pull/113

Check and see if the cores are on the mirrors in ~24hrs

**Comment by NikolaiHampton** [comment]
Tested XVIC on MacBook M2 and it worked perfectly. Thanks @garbear - now I can play The Count by Scott Adams again! :D 
Great work and I appreciate the effort you've all put in to maintaining this.
