### ISSUE TITLE
Analog stick does not work

### ISSUE THREAD

**Issue by mczerski** [kodi-game/game.libretro.vice_x64#7]
I have a ps3 dualshock controller. The issue is that analog stick does not work in emulator. Analog stick is working for sure in kodi as I can map it for example to up/down/left/right arrows in kodi. But if I map it through emulator settings it does not work.

I suspect that the problem is caused by the `type="RETRO_DEVICE_JOYPAD"` here:
https://github.com/kodi-game/game.libretro.vice_x64/blob/20083a8babefa585d0eee6b8c301b24532e31da2/game.libretro.vice_x64/resources/buttonmap.xml#L3

According to https://docs.libretro.com/development/input-api/ it should be `type="RETRO_DEVICE_ANALOG"`. But if I change the type to RETRO_DEVICE_ANALOG the pad is no longer working in the emulator (no signs of activity in status bar).

PS. What I want to achive is to map analog stick to up/down/left/right arrows alongside d-pad arrows.

**Comment by garbear** [comment]
> up/down/left/right arrows alongside d-pad arrows

Unfortunately, only one set can be active at once. If you want analog sticks to map to up/down/left/right in the emulator, you can map it in the controller configuration utility from the settings. You can't have both at once currently.

I intent to allow both analog sticks alongside the D-pad. The feature is called _surjective_ button mapping. Surjective buttonmapping will be possible when I complete the [Player Manager](https://github.com/garbear/xbmc/issues/87).

**Comment by mczerski** [comment]
I did not express myself clear. The issue is that analog stick (both, left and right) does not work at all in vice emulator regardless if it duplicates up/down/left/right arrows or not. According to [this](https://docs.libretro.com/library/vice/) I can remap retropad buttons and specifically I can remap left analog stick to any key (vice_mapper_lu, vice_mapper_ld, vice_mapper_ll, vice_mapper_lr). 
For test I remapped retropad up/down/left/right to some keybord keys and that was working as expected, but if I try to remap analog stick it does not work.
I had the same problem with amiga uae emulator, and after updating buttonmap.xml to [latest](https://github.com/kodi-game/game.libretro.uae/blob/master/game.libretro.uae/resources/buttonmap.xml) the issue was gone and I could use both analog sticks in the amiga emulator.

**Comment by garbear** [comment]
OK, I think I see what you mean. This should be fixed by https://github.com/kodi-game/game.libretro/pull/116. This was merged into the Omega (game.libretro version 21.0.5) ranch but not the Nexus branch. Is there any way you can give the Omega version a try?

It's possible that the PR I linked still hasn't fixed the problem. If that's the case, can you upload a full debug log?

**Comment by mczerski** [comment]
I patched game.libretro v20.2.3 with https://github.com/kodi-game/game.libretro/pull/116 and it is working as expected now (I can use analog stick in vice emulator).
So I suppose that in kodi 21 the problem will be fixed. You can close the issue.
Thanks !!!

**Comment by garbear** [comment]
I was mistaken, the fix was backported to Nexus and is actually in version 20.2.6. Is there any reason you're still on v20.2.3?

**Comment by mczerski** [comment]
I'm on the CoreELEC 20.2 which is the latest stable version (21-Omega is in beta) and game.libretro is in version 20.2.3. I can update game.libretro to 20.2.6 manually, thanks for the tip.

**Comment by mczerski** [comment]
I can confirm that version 20.2.6 also has no issues with analog sticks

**Comment by garbear** [comment]
Awesome! You could PR the update to CoreELEC if you want. I sent the update to LibreELEC, though I'm not sure if CoreELEC picks up LE updates.

**Comment by mczerski** [comment]
Looks like CoreELEC is already up to date with game.libretro on Nexus branch but there is no official release for IT yet.

**Comment by garbear** [comment]
Cool thanks for checking
